# fly.toml app configuration file generated for jetform-analytics on 2024-03-14T19:50:45+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jetform-analytics'
primary_region = 'sin'

[build]
  image = 'ghcr.io/umami-software/umami:postgresql-v2.10.2'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
